### ISSUE TITLE
Milestone 1: End to end for TwoSampleMR

### ISSUE THREAD

**Issue by chryswoods** [MRCIEU/gwasglue2#1]
* Create R package layout as a fork or new branch
* Create S3 class that replaces the current list of lists
* Add function to S3 class that converts from the object to the data needed as input to TwoSampleMR

**Comment by ritarasteiro** [comment]
We decided to use to use S4 class OOS.

**Comment by ritarasteiro** [comment]
We have a

**Comment by ritarasteiro** [comment]
I am closing this milestone and open one specific for harmonisation.
