### ISSUE TITLE
Harmonisation tests

### ISSUE THREAD

**Issue by explodecomputer** [MRCIEU/gwasglue2#16]
Need to create extensive testing for harmonisation - see the random datasets that were being generated for you to build the harmonisation function in the first place

**Comment by explodecomputer** [comment]
Added harmonisation test data here: https://github.com/MRCIEU/gwasglue2/tree/main/inst/testdata

To read:

```
read.csv(system.file("testdata", "harmonisation_scenarios.csv"), package="gwasglue2")
```

Rules

- if not assuming forward strand, don't handle multi-allelics, arrange the dataset alphabetically (rsid, a1, a2), then drop duplicates, then only merge on rsid
- if assuming forward strand, make internal identifier `variantid` that looks like chr_pos_a1_a2
    - a1 and a2 are alphabetical
    - if a1 or a2 is longer than 10 characters, create hash
    - if chr_pos not available then rsid_a1_a2 ?
    - switch effect allele to be the alphabetical allele
    - arrange dataset by `variant_id`

**Comment by ritarasteiro** [comment]
I was looking at different algorithms to create hashes and I first used the rlang::hash() function. This generates a 128-bit hash with a string of length 32, which I think is very long for a `variant_id`.
I think we should use 32-bit algorithms that return strings of length 8. The function [digest::digest()](http://dirk.eddelbuettel.com/code/digest.html) allows to choose several algorithms including 32-bit ones.
For example to compute a 32-bit hash with binary representation we can one of use these algorithms:

`
digest("aaggggggtttaaa",algo="crc32")
digest("aaggggggtttaaa",algo="xxhash32")
digest("aaggggggtttaaa",algo= "murmur32")
`
To have a hash computed with ASCII representation, we need to add the option ascii=TRUE

`
digest("aaggggggtttaaa",algo="crc32", ascii = TRUE)
digest("aaggggggtttaaa",algo="xxhash32", ascii = TRUE)
digest("aaggggggtttaaa",algo= "murmur32", ascii = TRUE)
`
